name: eage-hackathon-streamlit
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - requests
  - matplotlib
  - pandas
  - pip
  - streamlit
  - openai
  - nltk
  - pip:
    - bs4
    - langchain
    - faiss-cpu
